server:
  port: 8889

  servlet:
    context-path: /

  tomcat:
    uri-encoding: UTF-8
    threads:
      min-spare: 50
      max: 1000
management:

  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: module-seller
