server:
  port: 8888
  servlet:
    context-path: /
  netty:
    connection-timeout:
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: module-buyer
  cache:
    type: redis
  #Phân tích JSON bằng Jackson
  jackson:
    time-zone: GMT+8
    serialization:
      #Tắt chức năng giải mã JSON của Jackson.
      fail-on-empty-beans: false
  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      lettuce:
        pool:
          # Maximum number of connections in the connection pool (negative value means no limit), default is 8
          max-active: 200
          # Maximum blocking wait time for the connection pool (negative value means no limit), default is -1
          max-wait: 20
          # Maximum idle connections in the connection pool, default is 8
          max-idle: 10
          # Minimum idle connections in the connection pool, default is 8
          min-idle: 8
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/myShop?allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 811212
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 150
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 500
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    props:
      #Có nên in các câu lệnh SQL logic và các câu lệnh SQL thực tế hay không. Nên in trong quá trình gỡ lỗi và đóng trong môi trường sản xuất.
      sql:
        show: false

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #đã bật bộ đệm
    cache-enabled: true

myshop:
  cache:
    # Thời gian hết hạn tính bằng giây. Nếu nó không bao giờ hết hạn, nó được đặt thành -1.
    timeout: 1500
  # Cài đặt chi tiết JWT
  jwt-setting:
    # Thời gian hết hạn của token (phút)
    tokenExpireTime: 60

